export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_LENGTH_SUCCESS = 'GET_CONTACTS_LENGTH_SUCCESS';

export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED';
